# This file was added for TechDocs in Unity Internal Developer Portal http://go/docs-techdocs
# For more information on the configuration below see https://www.mkdocs.org/user-guide/configuration/
site_name: cse-memory-snapshot-data-tool
repo_url: https://github.com/Unity-Technologies/cse-memory-snapshot-data-tool
repo_name: GitHub
docs_dir: docs
edit_uri: "edit/main/docs/"
strict: true
plugins:
  - techdocs-core
nav:
  - About TechDocs: "index.md"
  - Introduction to cse-memory-snapshot-data-tool: "intro.md"
  - Architecture and design: "design.md"
  - Snap File Format: "snap-file-format.md"
  - SQL safety: "sql-safety.md"
  - Installing for local development: "installation.md"
  - Troubleshooting: "troubleshooting.md"
  - Runbook: "runbook.md"
